name = "dream"
version = "2.3.1"
description = "Clean, composable web development for Gleam. No magic."
licences = ["MIT"]
repository = { type = "github", user = "TrustBound", repo = "dream" }
links = [
    { title = "Documentation", href = "https://hexdocs.pm/dream" },
    { title = "GitHub", href = "https://github.com/TrustBound/dream" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_json = ">= 2.2.0 and < 4.0.0"
gleam_time = ">= 1.5.0 and < 2.0.0"
marceau = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
squirrel = ">= 4.0.0 and < 5.0.0"
mockth = { git = "https://github.com/bondiano/mockth.git", ref = "master" }
dream_test = ">= 1.0.3 and < 2.0.0"
dream_http_client = ">= 2.1.1 and < 3.0.0"
