name = "dream_example_static"
version = "0.1.0"
description = "Static file serving example"
licences = ["MIT"]

[dependencies]
dream = { path = "../.." }
dream_helpers = { path = "../../modules/helpers" }
mist = ">= 5.0.3 and < 6.0.0"
marceau = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

