name = "dream_helpers"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.44.0"
gleam_json = ">= 2.0.0"
gleam_time = ">= 1.5.0"
dream = { path = "../../" }

[dev-dependencies]
gleeunit = ">= 1.0.0"
mockth = { git = "https://github.com/bondiano/mockth.git", ref = "master" }

