name = "streaming_capabilities"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0"
gleam_http = ">= 3.6.0"
gleam_yielder = ">= 0.3.0"
dream = { path = "../../" }
dream_http_client = ">= 2.0.0 and < 3.0.0"
dream_mock_server = ">= 1.0.0 and < 2.0.0"

