name = "dream_opensearch"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.44.0"
gleam_json = ">= 2.0.0"
gleam_http = ">= 3.6.0"
gleam_httpc = ">= 2.3.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"

