name = "dream_example_database"
version = "0.1.0"
description = "Database example - full CRUD with PostgreSQL"
licences = ["MIT"]

[dependencies]
dream = { path = "../.." }
dream_helpers = { path = "../../modules/helpers" }
dream_postgres = { path = "../../modules/postgres" }
mist = ">= 5.0.3 and < 6.0.0"
pog = ">= 4.0.0 and < 5.0.0"
cigogne = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 2.2.0 and < 4.0.0"
gleam_time = ">= 1.5.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

