name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Erlang and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.13.0"
          rebar3-version: "3"

      - name: Download dependencies
        run: gleam deps download

      - name: Check code format
        run: gleam format --check

      - name: Build project
        run: gleam build

      - name: Run all unit tests
        env:
          CI: "true"
        run: make test-unit

  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dream_example_database_db
        ports:
          - 5435:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Erlang and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.13.0"
          rebar3-version: "3"
          elixir-version: "1.18"

      - name: Download dependencies
        run: gleam deps download

      - name: Build project
        run: gleam build

      - name: Setup database examples
        env:
          PGPASSWORD: postgres
          DATABASE_URL: postgres://postgres:postgres@localhost:5435/dream_example_database_db
        run: |
          psql -h localhost -p 5435 -U postgres -c "CREATE DATABASE dream_example_multi_format_db;" || true
          cd examples/database
          gleam deps download
          gleam run -m cigogne all
          cd ../multi_format
          gleam deps download
          export DATABASE_URL=postgres://postgres:postgres@localhost:5435/dream_example_multi_format_db
          gleam run -m cigogne all

      - name: Run all integration tests
        env:
          CI: "true"
          DATABASE_URL: postgres://postgres:postgres@localhost:5435/dream_example_database_db
          POSTGRES_PORT: "5435"
        run: make test-integration
